USE sample;

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS item;
CREATE TABLE item
(
    id INTEGER PRIMARY KEY AUTO_INCREMENT COMMENT 'ID',
    name VARCHAR(10) COMMENT '名前',
    price INTEGER COMMENT '価格',
    type INTEGER COMMENT '種類'
)
;